import { Injectable, BadRequestException, UnauthorizedException } from '@nestjs/common'; import crypto from 'crypto';
import Decimal from 'decimal.js'; import { QueueService } from '../queue/queue.service'; import { PostgresService } from '../db/postgres.service'; import { SendSmsDto } from './dto/send-sms.dto';
function normalizeMsisdn(v:string){const d=v.replace(/\\D/g,''); if(d.startsWith('880')) return d; if(d.startsWith('0')) return '880'+d.slice(1); return '880'+d;}
function parts(body:string,unicode:boolean){const n=Array.from(body).length; return unicode ? (n<=70?1:Math.ceil(n/67)) : (n<=160?1:Math.ceil(n/153));}
@Injectable() export class SmsService { constructor(private readonly queue:QueueService,private readonly db:PostgresService){}
 async send(dto:SendSmsDto,userIdHeader?:string){if(!userIdHeader)throw new UnauthorizedException('x-user-id is required'); const userId=BigInt(userIdHeader); if(!dto.to?.length)throw new BadRequestException('Recipient list is empty'); const batchExternal=crypto.randomUUID(); const jobs:any[]=[];
 await this.db.tx(async c=>{const u=await c.query('SELECT id,status,balance FROM "User" WHERE id=$1 FOR UPDATE',[userId.toString()]);if(!u.rowCount||u.rows[0].status!=='active')throw new UnauthorizedException('User is not active');let senderDbId:any=null;if(/^\\d+$/.test(dto.senderId)){const q=await c.query('SELECT id FROM "Sender" WHERE id=$1 AND "userId"=$2 AND status=$3',[dto.senderId,userId.toString(),'active']);if(q.rowCount)senderDbId=q.rows[0].id}else{const q=await c.query('SELECT id FROM "Sender" WHERE "userId"=$1 AND "senderId"=$2 AND status=$3',[userId.toString(),dto.senderId,'active']);if(q.rowCount)senderDbId=q.rows[0].id}if(!senderDbId)throw new BadRequestException('Sender not found or inactive');
 const b=await c.query('INSERT INTO "Batch" ("externalId","userId","senderId",body,status,"totalRecipients","validCount","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$6,NOW(),NOW()) RETURNING id',[batchExternal,userId.toString(),senderDbId,dto.body,'queued',dto.to.length]); let total='0';
 for(const rawTo of dto.to){const to=normalizeMsisdn(rawTo);const op=await c.query('SELECT o.id,o.code,p.prefix FROM "OperatorPrefix" p JOIN "Operator" o ON o.id=p."operatorId" WHERE p.enabled=true AND o.enabled=true AND $1 LIKE p.prefix || \'%\' ORDER BY length(p.prefix) DESC LIMIT 1',[to]);if(!op.rowCount)throw new BadRequestException('No operator mapping for '+rawTo);const rate=await c.query('SELECT tr."maskingPrice",tr."nonMaskingPrice" FROM "TariffRate" tr JOIN "TariffPlanAssignment" a ON a."tariffPlanId"=tr."tariffPlanId" WHERE a."userId"=$1 AND tr."operatorId"=$2 AND tr."effectiveFrom"<=NOW() ORDER BY a."effectiveFrom" DESC,tr."effectiveFrom" DESC LIMIT 1',[userId.toString(),op.rows[0].id]);if(!rate.rowCount)throw new BadRequestException('No tariff rate for operator '+op.rows[0].code);const unicode=dto.isUnicode??/[\\u0080-\\uFFFF]/u.test(dto.body);const messageParts=parts(dto.body,unicode);const unit=String(dto.senderId).length<=11?rate.rows[0].maskingPrice:rate.rows[0].nonMaskingPrice;const cost=new Decimal(String(unit)).mul(messageParts);if(!cost.isFinite()||cost.lte(0))throw new BadRequestException('Invalid SMS tariff');total=new Decimal(total).add(cost).toFixed(6);const externalId=crypto.randomUUID();await c.query('INSERT INTO "Message" ("externalId","userId","batchId","senderId",to,body,status,source,"isUnicode",parts,rate,cost,"createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,NOW(),NOW())',[externalId,userId.toString(),b.rows[0].id,senderDbId,to,dto.body,'queued','api',unicode,messageParts,unit,cost]);const job={id:crypto.randomUUID(),messageId:externalId,batchId:String(b.rows[0].id),provider:'InfoZillion',senderId:dto.senderId,to:[to],body:dto.body,isUnicode:unicode,isLongSMS:messageParts>1,createdAt:new Date().toISOString()}; jobs.push(job); await c.query('INSERT INTO "OutboxEvent" ("aggregateType","aggregateId","eventType",payload,"createdAt") VALUES ($1,$2,$3,$4,NOW())',['message',externalId,'sms.infozillion',JSON.stringify(job)]);}
 const amount=new Decimal(total);const before=new Decimal(String(u.rows[0].balance));if(before.lt(amount))throw new BadRequestException('Insufficient balance');const after=before.sub(amount);await c.query('UPDATE "User" SET balance=$1,"updatedAt"=NOW() WHERE id=$2',[after.toFixed(6),userId.toString()]);await c.query('INSERT INTO "Transaction" ("userId",amount,direction,"balanceBefore","balanceAfter",description,"createdAt") VALUES ($1,$2,$3,$4,$5,$6,NOW())',[userId.toString(),amount.toFixed(6),'debit',before.toFixed(6),after.toFixed(6),'SMS batch '+batchExternal]);});
 return {status:'accepted',provider:'InfoZillion',batchId:batchExternal,recipients:dto.to.length};} }